src/Pcf.Push.Dotnet.Core.Mvc.Windows/Models/Application.cs
namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Models
{
    public class Application
    {
        public string application_id { get; set; }
        public string application_name { get; set; }
        public string[] application_uris { get; set; }
        public string application_version { get; set; }
        public string cf_api { get; set; }
        public string host { get; set; }
        public string instance_id { get; set; }
        public string instance_index { get; set; }
        public Limits limits { get; set; }
        public string name { get; set; }
        public string port { get; set; }
        public string space_id { get; set; }
        public string space_name { get; set; }
        public string[] uris { get; set; }
        public string version { get; set; }
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Models/ErrorViewModel.cs
using System;

namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Models/Limits.cs
namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Models
{
    public class Limits
    {
        public string disk { get; set; }
        public string fds { get; set; }
        public string mem { get; set; }
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Controllers/DetailsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Pcf.Push.Dotnet.Core.Mvc.Windows.Models;
using System;
using System.Net;
using System.Runtime.InteropServices;

namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IConfiguration configuration;

        public DetailsController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }

        public IActionResult Index()
        {
            // environment variables
            var vcap_application = configuration["VCAP_APPLICATION"];

            var application = JsonConvert.DeserializeObject<Application>(vcap_application);

            var uris = String.Empty;
            foreach(var uri in application.uris)
            {
                uris += uri + ", ";
            }

            uris = uris.TrimEnd(' ', ',');

            ViewBag.Uris = uris;

            // runtime details
            ViewBag.OSDescription = RuntimeInformation.OSDescription;

            // host
            var hostname = Dns.GetHostName();
            var hostAddresses = Dns.GetHostAddresses(hostname);

            var addresses = String.Empty;
            foreach(var hostAddress in hostAddresses)
            {
                addresses += hostAddress.ToString() + ", ";
            }

            addresses = addresses.TrimEnd(' ', ',');

            ViewBag.HostName = hostname;
            ViewBag.HostAddress = addresses;

            //// system info
            //var currentProcess = Process.GetCurrentProcess();

            //ViewBag.TotalProcessorTime = currentProcess.TotalProcessorTime;

            return View(application);
        }
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Pcf.Push.Dotnet.Core.Mvc.Windows.Models;
using System.Diagnostics;

namespace Pcf.Push.Dotnet.Core.Mvc.Windows.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Views/Details/Index.cshtml
@model Application

<h2>Environment Variables</h2>

<hr />

<h4>VCAP_APPLICATION</h4>
<p></p>
<table class="table table-striped">
    <tr>
        <td>Application Id</td>
        <td>@Model.application_id</td>
    </tr>
    <tr>
        <td>Application Name</td>
        <td>@Model.application_name</td>
    </tr>
    <tr>
        <td>Application Version</td>
        <td>@Model.application_version</td>
    </tr>
    <tr>
        <td>Space Id</td>
        <td>@Model.space_id</td>
    </tr>
    <tr>
        <td>Space Name</td>
        <td>@Model.space_name</td>
    </tr>
    <tr>
        <td>URIs</td>
        <td>@ViewBag.Uris</td>
    </tr>
    <tr>
        <td>API</td>
        <td>@Model.cf_api</td>
    </tr>
    <tr>
        <td>Disk Limit</td>
        <td>@Model.limits.disk</td>
    </tr>
    <tr>
        <td>Memory</td>
        <td>@Model.limits.mem</td>
    </tr>
    <tr>
        <td>Instance Id</td>
        <td>@Model.instance_id</td>
    </tr>
    <tr>
        <td>Instance Index</td>
        <td>@Model.instance_index</td>
    </tr>
    <tr>
        <td>Port</td>
        <td>@Model.port</td>
    </tr>
</table>

<h2>Host</h2>

<hr />

<h4>OS</h4>
<p></p>
<table class="table table-striped">
    <tr>
        <td>Stack</td>
        <td>@ViewBag.OSDescription</td>
    </tr>
</table>

<h4>DNS</h4>
<p></p>
<table class="table table-striped">
    <tr>
        <td>Host Name</td>
        <td>@ViewBag.HostName</td>
    </tr>
    <tr>
        <td>Host Address</td>
        <td>@ViewBag.HostAddress</td>
    </tr>
</table>

src/Pcf.Push.Dotnet.Core.Mvc.Windows/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Windows</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/arrow.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Windows</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Details" asp-action="Index">Details</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - <a href="http://pivotal.io" target="_blank">Pivotal</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>